"""empty message

Revision ID: 9c6ee690afb6
Revises: cb42bf1aaf17
Create Date: 2023-01-31 23:13:25.916695

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9c6ee690afb6"
down_revision = "cb42bf1aaf17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("message", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contact")
    # ### end Alembic commands ###
